### ISSUE TITLE
[Feature Plan][Customize property] Template consumable objects

### ISSUE THREAD

**Issue by sandsieve** [lanyanxiang/habits-cli#19]
There might be the case that the user does not want to design their own consumables, so we can set some templates ready to be used.
For example:
1.1 Break card
     Take a break for 15 mins and still get the base reward for the time interval.
1.2 Vacation card
     Rest for a day and still get the base daily reward.
1.3 Reduce workload card (medium)
     Reduce the workload by 20% for an assigned mission/ rewarding action to get full reward.
1.4 Skip mission card
     Skip a daily mission, mark as complete and get the reward.
1.5 Redeem item card
     Redeem an item from the shop.
1.6 Reward boost card (small)
     Boost the reward for a mission/ rewarding action by 10% or boost the total reward for today for 5%.
etc.
Other templates and features will be designed later.

**Comment by lanyanxiang** [comment]
Thanks for bringing this up. Will look more into this soon.

**Comment by lanyanxiang** [comment]
I like the idea of having some templates, but I think more thoughts are needed to not make them too opinionated. Possibly we can let users define their own templates and have a marketplace, where users can just download random templates from other people and use them.

Will hold on to this for now.

**Comment by lanyanxiang** [comment]
@sandsieve Bump on this. Any thoughts?

**Comment by lanyanxiang** [comment]
As specified in the reason above, I'm closing this issue for now. Please reopen if you have any questions, thanks!
