### ISSUE TITLE
[Bug] Session still could not be persisted

### ISSUE THREAD

**Issue by evencewang** [lanyanxiang/habits-cli#41]
![Issue](https://user-images.githubusercontent.com/77359066/135373285-74916bf1-73cf-4b47-86c6-a801c2fcdffc.png)

**Comment by lanyanxiang** [comment]
This looks like a local libsecret problem. I'm not sure how to fix this, it might be very os dependent.

By the way, you can install habits CLI globally so you can call `habits` instead of `./habits`.

**Comment by lanyanxiang** [comment]
Do you think it's acceptable to have a configuration option that allows users who have trouble setting up `libsecret` to choose a location on their hard disk to store these tokens?

We can probably find a way to add an encryption key for different distributions of this package. 🤔

**Comment by evencewang** [comment]
I think that would be fine provided that I find the problem with the libsecret to begin with.

**Comment by lanyanxiang** [comment]
Yeah, let's have some further discussion on the items above and add another ticket for such configuration. That might take plenty of energy to implement, but if a lot of people are having trouble with this, it's definitely worth it. Closing this ticket for now.
