### ISSUE TITLE
[Bug] No error thrown when update values are identical

### ISSUE THREAD

**Issue by lanyanxiang** [lanyanxiang/habits-cli#52]
![image](https://user-images.githubusercontent.com/46196304/135958262-e982fc6e-100b-46c4-8e8e-87380aa4d6d6.png)

We would expect an error to be thrown if the current "change in amount" is the same as the new "change in amount".

**Comment by jimmy-lan** [comment]
As per discussion in #57, we will show a warning indicating which values are not updated to the user instead of an error blocking the update.

The warning message will be displayed outside of the table.
