### ISSUE TITLE
Strange things that caused the thing to not work for Evence

### ISSUE THREAD

**Issue by evencewang** [lanyanxiang/habits-cli#6]
![image](https://user-images.githubusercontent.com/77359066/132081952-a107bc68-226f-469e-8c33-c7312708db8c.png)

**Comment by lanyanxiang** [comment]
Was debugging this with Evence (author of issue) at the time. Adding some context:
1. This was run on Ubuntu 20.04
2. This happens when running `habits -V` in release package, `habits auth signup` in development package.

**Comment by lanyanxiang** [comment]
For anyone looking at this in the future, this issue was resolved after downgrading node version to `v12.x.x`. Was using `v16.8.x` when this error happened.

Closing this issue.
