### ISSUE TITLE
Could not persist secure session

### ISSUE THREAD

**Issue by evencewang** [lanyanxiang/habits-cli#7]
![image](https://user-images.githubusercontent.com/77359066/132082113-8bdb6454-9ed3-4360-b294-f0fb94fc70f6.png)

**Comment by lanyanxiang** [comment]
https://github.com/atom/node-keytar/issues/224 Seems to have some helpful information. In particular, https://github.com/atom/node-keytar/issues/224#issuecomment-540459884.

**Comment by lanyanxiang** [comment]
If you don't have `dbus` installed, run
```
sudo apt install -y dbus
```

**Comment by evencewang** [comment]
After following the D bus installation guide, as well as the solution from this page: 
https://github.com/atom/node-keytar/issues/74
The problem has been resolved. Closing the issue.
