### ISSUE TITLE
Issue with auth signin

### ISSUE THREAD

**Issue by evencewang** [lanyanxiang/habits-cli#8]
UnhandledPromiseRejectionWarning: Error: No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login

![image](https://user-images.githubusercontent.com/77359066/132082568-f453751c-d1ca-4436-9611-3e616b96d339.png)

**Comment by lanyanxiang** [comment]
Looks like a `libsecret` error. Maybe I should add this feature to warn the user when `libsecret` is not installed.

I guess it's also not easy to find a good installation guide for `libsecret`.

**Comment by lanyanxiang** [comment]
The linked pull request contains some work for a central error handler, so a correct error message should be shown to the user when there's a `libsecret` error. Closing this issue.
